### ISSUE TITLE
Obszar na brzegach BufferedImage

### ISSUE THREAD

**Issue by kbednarz** [PPiedel/AutoScreenBrightness#2]
Jak przeglądałem nasz inputImage, to obszar na brzegach zdjęcia jest z reguły ciemny, niezależnie od pomieszczenia. To fałszuje trochę odczyt jasności w pokoju. Jak to można poprawić? Jakiś algo biorący wagę(ważność) pikseli?

**Comment by PPiedel** [comment]
Spójrz na moje zdjęcia : http://postimg.org/gallery/2xvnmoy58/a3399b89/

Może masz ciemno w pomieszczeniu :P ?

**Comment by kbednarz** [comment]
Potwierdzam. Mam ciemno. Zamykam.
