### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by PPiedel** [PPiedel/AutoScreenBrightness#3]
Moze by tak ładnie pogrupować klasy do paczek ? Zgodnie z tym http://www.javapractices.com/topic/TopicAction.do?Id=205
proponuję system package-by-feature.

**Comment by PPiedel** [comment]
.... albo i nie. Sam nie wiem. Co o tym sądzisz ?

**Comment by kbednarz** [comment]
Można spróbować, tylko nie wiem, czy to nie za mały program. My nie mamy nawet żadnych folderów xD

**Comment by kbednarz** [comment]
A sorry, widzę, że podzieliłeś. Ok, jest dobrze :+1:
